.\" Copyright (C) 2006 Ganaël LAPLANCHE
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
.\" USA.
.\"
.\" Ganael Laplanche
.\" ganael.laplanche@martymac.com
.\" http://contribs.martymac.com
.\"
.TH ldapscripts 5 "January 1, 2006"
.LO 1

.SH NAME
ldapscripts \- Scripts to manage POSIX accounts in your LDAP directory.

.SH DESCRIPTION
The ldapscripts are a set of shell (sh) scripts to manage POSIX accounts in an OpenLDAP directory. They can be used as standalone tools or within Samba's smb.conf file. Each scripts matches a specific smb.conf option, except those beginning with an underscore ("_"), which are just "useful".

.SH REQUIREMENTS
The main requirements are the OpenLDAP client tools (ldapadd, ldapsearch, ldapdelete, ...). Other commands are called in the scripts but shoud come with your distro (sed, grep, cut, ...).

.SH CONFIGURATION
The main configuration of the ldapscripts is usually the /etc/ldapscripts/ldapscripts.conf file (or /usr/local/etc/ldapscripts/ldapscripts.conf, depending on your system). Modify it to fit your needs before using the scripts. Each script also uses a "runtime" file, usually /etc/ldapscripts/runtime (or /usr/local/etc/ldapscripts/runtime). You don't need to modify this file.

.SH "USING AS STANDALONE TOOLS"
The scripts can be used as standard command-line tools. Just call the script using correct arguments. Check the man page of the script or call it without any argument to get help.

.SH "USING WITH SAMBA"
As I've already explained, each script is designed to fit one configuration option of Samba. Modify you smb.conf file to call the scripts :

.nf
# [...]
add machine script = /usr/local/bin/ldapaddmachine '%u' sambamachines
add user script = /usr/local/bin/ldapadduser '%u' sambausers
add group script = /usr/local/bin/ldapaddgroup '%g'
add user to group script = /usr/local/bin/ldapaddusertogroup '%u' '%g'
delete user script = /usr/local/bin/ldapdeleteuser '%u'
delete group script = /usr/local/bin/ldapdeletegroup '%g'
delete user from group script = /usr/local/bin/ldapdeleteuserfromgroup '%u' '%g'
set primary group script = /usr/local/bin/ldapsetprimarygroup '%u' '%g'
rename user script = /usr/local/bin/ldaprenameuser '%uold' '%unew'
# [...]

.SH "SEE ALSO"
_ldapdeletemachine(1), _ldapmodifymachine(1), _ldaprenamemachine(1), ldapadduser(1), ldapdeleteuserfromgroup(1),
_ldapfinger(1), _ldapmodifyuser(1), _lsldap(1), ldapaddusertogroup(1), ldaprenameuser(1), _ldapinit(1),
_ldappasswd(1), ldapaddgroup(1), ldapdeletegroup(1), ldapsetprimarygroup(1), _ldapmodifygroup(1), _ldaprenamegroup(1),
ldapaddmachine(1), ldapdeleteuser(1).

.SH AVAILABILITY
The ldapscripts are provided under the GNU General Public License v2 (see COPYING for more details).
The latest version of the ldapscripts is available on :
.B http://contribs.martymac.com
