#!/bin/sh

#  Copyright (C) 2005 Ganaël LAPLANCHE - Linagora
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#  USA.

# Specify absolute paths here
BINDIR="/usr/local/bin"
MANDIR="/usr/share/man"
ETCDIR="/etc/ldapscripts"
RUNTIMEDIR="/etc/ldapscripts"
ETCFILE="ldapscripts.conf"
RUNTIMEFILE="runtime"

# Prepare sources
sed -i.orig -e "s|^_RUNTIMEFILE=.*|_RUNTIMEFILE=\"${RUNTIMEDIR}/${RUNTIMEFILE}\"|g" bin/*
sed -i.orig -e "s|^_CONFIGFILE=.*|_CONFIGFILE=\"${ETCDIR}/${ETCFILE}\"|g" etc/*

# Script files
mkdir -p "${BINDIR}" 2>/dev/null
cp -f bin/_ldapdeletemachine "${BINDIR}"
cp -f bin/_ldaprenamegroup "${BINDIR}"
cp -f bin/_ldaprenamemachine "${BINDIR}"
cp -f bin/_ldapinit "${BINDIR}"
cp -f bin/_lsldap "${BINDIR}"
cp -f bin/_ldappasswd "${BINDIR}"
cp -f bin/ldapaddgroup "${BINDIR}"
cp -f bin/ldapadduser "${BINDIR}"
cp -f bin/ldapdeletegroup "${BINDIR}"
cp -f bin/ldapdeleteuserfromgroup "${BINDIR}"
cp -f bin/ldapsetprimarygroup "${BINDIR}"
cp -f bin/ldapaddmachine "${BINDIR}"
cp -f bin/ldapaddusertogroup "${BINDIR}"
cp -f bin/ldapdeleteuser "${BINDIR}"
cp -f bin/ldaprenameuser "${BINDIR}"

# Man pages
mkdir -p "${MANDIR}"/man1 2>/dev/null
for i in man/man1/*
do
	cat "${i}" | gzip - > "${MANDIR}"/man1/`basename ${i}`.gz
done
mkdir -p "${MANDIR}"/man5 2>/dev/null
for i in man/man5/*
do
	cat "${i}" | gzip - > "${MANDIR}"/man5/`basename ${i}`.gz
done

# Configuration and runtime files
mkdir -p "${ETCDIR}" 2>/dev/null
if [ -f "${ETCDIR}/${ETCFILE}" ]
then
  mv -f "${ETCDIR}/${ETCFILE}" "${ETCDIR}/${ETCFILE}.old"
  echo "Old configuration file found, saved as ${ETCDIR}/${ETCFILE}.old"
fi
cp -f etc/ldapscripts.conf "${ETCDIR}/${ETCFILE}"

mkdir -p "${RUNTIMEDIR}" 2>/dev/null
cp -f etc/runtime "${RUNTIMEDIR}/${RUNTIMEFILE}"

echo "The ldapscripts are now installed ! See README for more details..."
