#!/bin/sh

# ldapdeleteuserfromgroup : deletes a memberUid attribute from a POSIX group in LDAP

#  Copyright (C) 2005 Ganaël LAPLANCHE - Linagora
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#  USA.

if [ "$1" == "" ] || [ "$2" == "" ]
then
  echo "Usage : $0 <username> <goupname | gid>"
  exit -1
fi

# Read configuration
if [ ! -f /etc/ldapscripts/ldapscripts.conf ]
then
  echo "Unable to read configuration file from /etc/ldapscripts/ldapscripts.conf, exiting..." | tee -a "$LOGFILE"
  exit -1
fi

source /etc/ldapscripts/ldapscripts.conf

# Set username
_UID="$1"

# Check groupname : $2, must exist in LDAP !
_GID=`$LDAPSEARCHBIN -w "$BINDPWD" -D "$BINDDN" -b "$GSUFFIX,$SUFFIX" -xH "ldap://$SERVER" -s sub -LLL "(&(objectClass=posixGroup)(memberUid=$1)(|(cn=$2)(gidNumber=$2)))" cn 2>>"$LOGFILE" | grep "cn: " | head -n 1 | sed -e "s|cn: ||"`
if [ "$_GID" == "" ] # Group not found
then
  echo "Group $2 not found (or $1 is not a member of group $2)" | tee -a "$LOGFILE"
  exit -1
fi

# Modify group entry
grep -E '^##' "$0" | sed 's|^##||' | \
        sed -e "s|<group>|$_GID|g" -e "s|<gsuffix>|$GSUFFIX|g" -e "s|<suffix>|$SUFFIX|g" -e "s|<uid>|$_UID|g" | \
        $LDAPMODIFYBIN -w "$BINDPWD" -D "$BINDDN" -xH "ldap://$SERVER" 2>>"$LOGFILE" 1>/dev/null

if [ $? -ne 0 ]
then
  echo "Error deleting user $_UID from group $_GID" | tee -a "$LOGFILE"
  exit -1
fi

echo "Successfully deleted user $_UID from group $_GID" | tee -a "$LOGFILE"
exit 0

# Ldif info ##################################
##dn: cn=<group>,<gsuffix>,<suffix>
##changetype: modify
##delete: memberUid
##memberUid: <uid>
