#!/bin/sh

#  ldapaddusertogroup : adds a memberUid attribute to a POSIX group in LDAP

#  Copyright (C) 2005 Ganaël LAPLANCHE - Linagora
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#  USA.

if [ "$1" = "" ] || [ "$2" = "" ]
then
  echo "Usage : $0 <username | uid> <goupname | gid>"
  exit 1
fi

# Read configuration
if [ ! -f /etc/ldapscripts/ldapscripts.conf ]
then
  echo "Unable to read configuration file from /etc/ldapscripts/ldapscripts.conf, exiting..." | tee -a "$LOGFILE"
  exit 1
fi

. /etc/ldapscripts/ldapscripts.conf

# Check username : $1
_UID=`$GETENTPWCMD "$1" | head -n 1 | cut -d ":" -f 1` # Convert to name any user passed in as name/uid
if [ "$_UID" = "" ] # User not found
then
  echo "Warning : user $1 not found, using it anyway..." | tee -a "$LOGFILE"
  _UID="$1"
fi

# Check groupname : $2, must exist in LDAP !
_GID=`$LDAPSEARCHBIN -w "$BINDPWD" -D "$BINDDN" -b "$GSUFFIX,$SUFFIX" -xH "ldap://$SERVER" -s sub -LLL "(&(objectClass=posixGroup)(!(memberUid=$_UID))(|(cn=$2)(gidNumber=$2)))" cn 2>>"$LOGFILE" | grep "cn: " | head -n 1 | sed -e "s|cn: ||"`
if [ "$_GID" = "" ] # Group not found
then
  echo "Group $2 not found (or $_UID already member of $2)" | tee -a "$LOGFILE"
  exit 1
fi

# Modify group entry
grep -E '^##' "$0" | sed 's|^##||' | \
        sed -e "s|<group>|$_GID|g" -e "s|<suffix>|$SUFFIX|g" -e "s|<gsuffix>|$GSUFFIX|g" -e "s|<uid>|$_UID|g" | \
        $LDAPMODIFYBIN -w "$BINDPWD" -D "$BINDDN" -xH "ldap://$SERVER" 2>>"$LOGFILE" 1>/dev/null

if [ $? -ne 0 ]
then
  echo "Error adding user $_UID to group $_GID" | tee -a "$LOGFILE"
  exit 1
fi

echo "Successfully added user $_UID to group $_GID" | tee -a "$LOGFILE"
exit 0

# Ldif info ##################################
##dn: cn=<group>,<gsuffix>,<suffix>
##changetype: modify
##add: memberUid
##memberUid: <uid>
