#!/bin/sh

#  ldaprenameuser : renames a POSIX user account in LDAP

#  Copyright (C) 2006-2019 Ganaël LAPLANCHE
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#  USA.

if [ -z "$1" ] || [ -z "$2" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
  echo "Usage : $0 <old username | uid> <new username>"
  exit 1
fi

# Source runtime file
_RUNTIMEFILE="/usr/lib/ldapscripts/runtime"
. "$_RUNTIMEFILE"

# Find dest username : $2 must not exist in LDAP !
_findentry "$USUFFIX,$SUFFIX" "(&(objectClass=posixAccount)(uid=$2))"
[ -z "$_ENTRY" ] || end_die "User $2 already exists in LDAP"

# Find src username : $1 must exist in LDAP !
_findentry "$USUFFIX,$SUFFIX" "(&(objectClass=posixAccount)(|(uid=$1)(uidNumber=$1)))"
[ -z "$_ENTRY" ] && end_die "User $1 not found in LDAP"

# Store _UID and _UDN for filters
if [ "$GCLASS" = "posixGroup" ]
then
  _getattribute "$_ENTRY" "uid"
  [ -z "$_ATTRIBUTE" ] && end_die "Error getting user attribute from LDAP (uid)"
  _UID="$_ATTRIBUTE"
fi
_UDN="$_ENTRY"

# Rename entry
_ldaprename "$_ENTRY" "uid=$2" || end_die "Error renaming user $_ENTRY to $2 in LDAP"

# Store _NEWUID and _NEWUDN for filters
_findentry "$USUFFIX,$SUFFIX" "(&(objectClass=posixAccount)(uid=$2))"
[ -z "$_ENTRY" ] && end_die "Renamed user $2 not found in LDAP"
_NEWUID="$2"
_NEWUDN="$_ENTRY"

# Finally, rename this user in all his secondary groups
case $GCLASS in
  posixGroup)
    _findentries "$GSUFFIX,$SUFFIX" "(&(objectClass=posixGroup)(memberUid=$_UID))"
    [ -n "$_ENTRIES" ] && echo "$_ENTRIES" | \
    while read _ENTRY
    do
      echo_log "Renaming user in secondary group: $_ENTRY"
      # Modify group entry
      _extractldif 2 | _filterldif | _utf8encode | _ldapmodify
    done
  ;;
  *)
    _findentries "$GSUFFIX,$SUFFIX" "(&(objectClass=$GCLASS)($_GMEMBERATTR=$_UDN))"
    [ -n "$_ENTRIES" ] && echo "$_ENTRIES" | \
    while read _ENTRY
    do
      echo_log "Renaming user in secondary group: $_ENTRY"
      # Modify group entry
      _extractldif 3 | _filterldif | _utf8encode | _ldapmodify
    done
  ;;
esac

end_ok "Successfully renamed user $_UDN to $_NEWUID in LDAP"

# Ldif templates #################################
#
# PosixGroup (level "2") :
##dn: <entry>
##changetype: modify
##delete: <gmemberattr>
##<gmemberattr>: <uid>
##-
##add: <gmemberattr>
##<gmemberattr>: <newuid>
#
# Others (level "3") :
###dn: <entry>
###changetype: modify
###delete: <gmemberattr>
###<gmemberattr>: <udn>
###-
###add: <gmemberattr>
###<gmemberattr>: <newudn>
