#!/bin/sh

#  ldaprenamegroup : renames a POSIX group in LDAP

#  Copyright (C) 2006-2011 Ganaël LAPLANCHE
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#  USA.

if [ -z "$1" ] || [ -z "$2" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
  echo "Usage : $0 <old groupname | gid> <new groupname>"
  exit 1
fi

# Source runtime file
_RUNTIMEFILE="/usr/lib/ldapscripts/runtime"
. "$_RUNTIMEFILE"

# Find dest groupname : $2 must not exist in LDAP !
# Note : as posixGroup is a common objectClass to all supported GCLASSes 
# (we use RFC 2307bis AUXILIARY posixGroups), look for it instead of $GCLASS,
# which would be too specific here and could miss posixGroup-only entries.
_findentry "$GSUFFIX,$SUFFIX" "(&(objectClass=posixGroup)(cn=$2))"
[ -z "$_ENTRY" ] || end_die "Group $2 already exists in LDAP"

# Find src groupname : $1 must exist in LDAP !
_findentry "$GSUFFIX,$SUFFIX" "(&(objectClass=$GCLASS)(|(cn=$1)(gidNumber=$1)))"
[ -z "$_ENTRY" ] && end_die "Group $1 not found in LDAP"

# Rename entry
_ldaprename "$_ENTRY" "cn=$2" || end_die "Error renaming group $_ENTRY to $2 in LDAP"
end_ok "Successfully renamed group $_ENTRY to $2 in LDAP"
