#!/bin/sh

#  ldapaddgroup : adds a POSIX group entry to LDAP

#  Copyright (C) 2005 Ganaël LAPLANCHE - Linagora
#  Copyright (C) 2006-2011 Ganaël LAPLANCHE
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#  USA.

if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
  echo "Usage : $0 <groupname> [gid]"
  exit 1
fi

# Source runtime file
_RUNTIMEFILE="/usr/lib/ldapscripts/runtime"
. "$_RUNTIMEFILE"

# Group name
_GROUP="$1"

# Group GID
if [ -z "$2" ] # No argument, we must find a correct GID
then
  _GID=$(_findnextgid)
  [ -z "_GID" ] && end_die "Cannot guess next free group id"
else
  _GID="$2"
fi

# Use template if necessary
if [ -n "$GTEMPLATE" ] && [ -r "$GTEMPLATE" ]
then
  _getldif="cat $GTEMPLATE"
else
  case $GCLASS in
    posixGroup)
    _getldif="_extractldif 2"
    ;;
    *)
    _getldif="_extractldif 3"
    ;;
  esac
fi

# Add user to LDAP
$_getldif | _filterldif | _askattrs | _utf8encode | _ldapadd

[ $? -eq 0 ] || end_die "Error adding group $_GROUP to LDAP"
end_ok "Successfully added group $_GROUP to LDAP"

# Ldif templates #################################
#
# PosixGroup (level "2") :
##dn: cn=<group>,<gsuffix>,<suffix>
##objectClass: <gclass>
##cn: <group>
##gidNumber: <gid>
##description: Group account
#
# Others (level "3") - RFC 2307bis :
###dn: cn=<group>,<gsuffix>,<suffix>
###objectClass: posixGroup
###objectClass: <gclass>
###cn: <group>
###gidNumber: <gid>
###description: Group account
###<gmemberattr>: <gdummymember>
