#!/bin/sh

#  ldapaddusertogroup : adds a member to a group in LDAP

#  Copyright (C) 2005 Ganaël LAPLANCHE - Linagora
#  Copyright (C) 2006-2011 Ganaël LAPLANCHE
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#  USA.

if [ -z "$1" ] || [ -z "$2" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
  echo "Usage : $0 <username | uid | dn> <groupname | gid>"
  exit 1
fi

# Source runtime file
_RUNTIMEFILE="/usr/lib/ldapscripts/runtime"
. "$_RUNTIMEFILE"

case $GCLASS in
  posixGroup)
    # Check username : $1
    _UID=$(_uidtouser "$1")
    [ -z "$_UID" ] && end_die "Cannot resolve uid $1 to user : not found"
    # Check groupname : $2 must exist in LDAP !
    _GID=$(_ldapsearch "$GSUFFIX,$SUFFIX" "(&(objectClass=posixGroup)(!(memberUid=$_UID))(|(cn=$2)(gidNumber=$2)))" cn | grep "cn: " | head -n 1 | sed "s|cn: ||")
    [ -z "$_GID" ] && end_die "Group $2 not found (or $_UID already member of $2)"
 
    # Modify group entry
    _extractldif 2 | _filterldif | _utf8encode | _ldapmodify
  ;;
  *)
    if is_valid_dn "$1"
    then
      # DN supplied as first argument, check it : $1 must exist in LDAP !
      _getattribute "$1" "uid"
      [ -z "$_ATTRIBUTE" ] && end_die "User DN $1 not found in LDAP"
      # DN is OK, keep it
      _UDN="$1"
    else
      # UID or username supplied, check it : $1 must exist in LDAP !
      _UDN=$(_uidtodn "$1")
      [ -z "$_UDN" ] && end_die "Cannot resolve uid $1 to DN : not found"
    fi
    # Check groupname : $2 must exist in LDAP !
    _GID=$(_ldapsearch "$GSUFFIX,$SUFFIX" "(&(objectClass=$GCLASS)(!($_GMEMBERATTR=$_UDN))(|(cn=$2)(gidNumber=$2)))" cn | grep "cn: " | head -n 1 | sed "s|cn: ||")
    [ -z "$_GID" ] && end_die "Group $2 not found (or $_UDN already member of $2)"
 
    # Modify group entry
    _extractldif 3 | _filterldif | _utf8encode | _ldapmodify
  ;;
esac
 
[ $? -eq 0 ] || end_die "Error adding user ${_UID}${_UDN} to group $_GID"
end_ok "Successfully added user ${_UID}${_UDN} to group $_GID"
 
# Ldif templates #################################
#
# PosixGroup (level "2") :
##dn: cn=<gid>,<gsuffix>,<suffix>
##changetype: modify
##add: <gmemberattr>
##<gmemberattr>: <uid>
#
# Others (level "3") :
###dn: cn=<gid>,<gsuffix>,<suffix>
###changetype: modify
###add: <gmemberattr>
###<gmemberattr>: <udn>
