.\" Copyright (C) 2006-2011 Ganaël LAPLANCHE
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
.\" USA.
.\"
.\" Ganael Laplanche
.\" ganael.laplanche@martymac.org
.\" http://contribs.martymac.org
.\"
.TH ldaprenamegroup 1 "January 1, 2006"

.SH NAME
ldaprenamegroup \- renames a POSIX group in LDAP.

.SH SYNOPSIS
.B ldaprenamegroup
.RB <old\ groupname | gid>
.RB <new\ groupname>
 
.SH OPTIONS
.TP
.B <old groupname | gid>
The old name or gid of the group to rename.
.TP
.B <new groupname>
The new name of the group.

.SH "SEE ALSO"
ldaprenameuser(1), ldaprenamemachine(1), ldapscripts(5).

.SH AVAILABILITY
The ldapscripts are provided under the GNU General Public License v2 (see COPYING for more details).
The latest version of the ldapscripts is available on :
.B http://contribs.martymac.org

.SH BUGS
No bug known.
