.\" Copyright (C) 2009-2011 Ganaël LAPLANCHE
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
.\" USA.
.\"
.\" Ganael Laplanche
.\" ganael.laplanche@martymac.org
.\" http://contribs.martymac.org
.\"
.TH ldapgid 1 "January 23, 2009"

.SH NAME
ldapgid \- displays a group's list of IDs the way ldapid(1) does.

.SH SYNOPSIS
.B ldapgid
.RB [-P] <groupname | gid>
 
.SH DESCRIPTION
.TP
The following is displayed : gid=gidNumber(cn) users(primary)=uidNumber(uid)[,uidNumber(uid)...] users(secondary)=uidNumber(uid)[,uidNumber(uid)...].
.TP
users(primary) lists users having the group declared as their primary group. users(secondary) lists users using the group as a secondary one.

.SH OPTIONS
.TP
.B <groupname | gid>
Group name or GID of a group to show information about.
.TP
.B [-P]
Display group information as a /etc/group file entry.

.SH "SEE ALSO"
ldapid(1), lsldap(1), ldapfinger(1), ldapscripts(5).

.SH AVAILABILITY
The ldapscripts are provided under the GNU General Public License v2 (see COPYING for more details).
The latest version of the ldapscripts is available on :
.B http://contribs.martymac.org

.SH BUGS
No bug known.
