.\" Copyright (C) 2007-2011 Ganaël LAPLANCHE
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
.\" USA.
.\"
.\" Ganael Laplanche
.\" ganael.laplanche@martymac.org
.\" http://contribs.martymac.org
.\"
.TH ldapfinger 1 "February 1, 2007"

.SH NAME
ldapfinger \- displays a user/machine/group POSIX account's details.

.SH SYNOPSIS
.B ldapfinger
.RB [-u | -g | -m] [username | machinename | groupname | uid | gid]
 
.SH OPTIONS
.TP
.B [username | machinename | groupname | uid | gid]
The name or id of the user, machine (with an ending $) or group you want to display. You may use a wildcard here to look for substrings. e.g. 'marty*' or '*mart*'. Acts on current user if nothing is specified.
.TP
.B [-u]
Look for users only (by default, search the whole directory).
.TP
.B [-g]
Look for groups only (by default, search the whole directory).
.TP
.B [-m]
Look for machines only (by default, search the whole directory).

.SH "SEE ALSO"
lsldap(1), ldapid(1), ldapgid(1), ldapscripts(5).

.SH AVAILABILITY
The ldapscripts are provided under the GNU General Public License v2 (see COPYING for more details).
The latest version of the ldapscripts is available on :
.B http://contribs.martymac.org

.SH BUGS
No bug known.
