.\" Copyright (C) 2006-2011 Ganaël LAPLANCHE
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
.\" USA.
.\"
.\" Ganael Laplanche
.\" ganael.laplanche@martymac.org
.\" http://contribs.martymac.org
.\"
.TH ldapdeletegroup 1 "January 1, 2006"

.SH NAME
ldapdeletegroup \- deletes a POSIX group account from LDAP.

.SH SYNOPSIS
.B ldapdeletegroup
.RB <groupname | gid>

.SH OPTIONS
.TP
.B <groupname | gid>
The name or gid of the group to delete.

.SH "SEE ALSO"
ldapdeleteuser(1), ldapdeletemachine(1), ldapscripts(5).

.SH AVAILABILITY
The ldapscripts are provided under the GNU General Public License v2 (see COPYING for more details).
The latest version of the ldapscripts is available on :
.B http://contribs.martymac.org

.SH LIMITATIONS
A user's primary group can be deleted ; the user entry will NOT be updated. This means the user will belong to a group that not longer exists.

.SH BUGS
No bug known.
